const products = [
    {
        _id: '1',
        name: 'Hydrogen',
        image: '',
        description: '',
        brand: '',
        category: '',
        price: 89.9,
        countInStock: 3,
        rating: 4.5,
        numReviews: 4, 
    },
    {
        _id: '2',
        name: 'Helium',
        image: '',
        description: '',
        brand: '',
        category: '',
        price: 799.9,
        countInStock:5,
        rating: 4.1,
        numReviews: 9, 
    },
    {
        _id: '3',
        name: 'Lithium',
        image: '',
        description: '',
        brand: '',
        category: '',
        price: 104.9,
        countInStock: 2,
        rating: 4.7,
        numReviews: 10, 
    },
    {
        _id: '4',
        name: 'Berylium',
        image: '',
        description: '',
        brand: '',
        category: '',
        price: 90.9,
        countInStock: 3,
        rating: 4.2,
        numReviews: 7, 
    },
    {
        _id: '5',
        name: 'Boron',
        image: '',
        description: '',
        brand: '',
        category: '',
        price: 99.9,
        countInStock: 5,
        rating: 4.5,
        numReviews: 4, 
    },
    {
        _id: '6',
        name: 'Carbon',
        image: '',
        description: '',
        brand: '',
        category: '',
        price: 89.9,
        countInStock: 3,
        rating: 4.0,
        numReviews: 2, 
    },
]
export default products